### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Mihoshika** [viral32111/black-hole-cache#1]
Once I started using the Black Hole Cache™, I couldn't stop. I guess what they say is true. "Once you go black, you never go back."

**Comment by viral32111** [comment]
Either that or you're too lazy to setup other resource generators 😛 

On an unrelated note, are you going to come back to the Discord server?

**Comment by gabunne** [comment]
the only thing black is the huge cock I take

**Comment by Mihoshika** [comment]
Pc still busted. PCU + PCU port busted. Can't afford to fix until I get a
new job.

**Comment by viral32111** [comment]
Fair enough, I assumed you had got everything fixed when I saw this issue.

**Comment by Mihoshika** [comment]
Nah
Just been on phone reading a ton of WNs/LNs, and applying to dozens of jobs
a day.

**Comment by JpnRndr01** [comment]
Miho its good to see that ur still alive lol, I hope you get a new job and can afford a new pc, discord really aint the same without you :D
